In [1]:
import numpy as np
import sys
import time

In [3]:
print("______________________________________________________________")
print("______________________________________________________________")
print("______________________________________________________________")
print("______________________________________________________________")
print("______________________________________________________________")
print("______________________________________________________________")
print("______________________________________________________________\n")
print("____________Day 1 of numpy date 12 aug , 2025_________________\n")
print("______________________________________________________________")
print("______________________________________________________________")
print("______________________________________________________________")
print("______________________________________________________________")
print("______________________________________________________________")
print("______________________________________________________________")
print("______________________________________________________________")

______________________________________________________________
______________________________________________________________
______________________________________________________________
______________________________________________________________
______________________________________________________________
______________________________________________________________
______________________________________________________________

____________Day 1 of numpy date 12 aug , 2025_________________

______________________________________________________________
______________________________________________________________
______________________________________________________________
______________________________________________________________
______________________________________________________________
______________________________________________________________
______________________________________________________________


In [16]:
print("___ 1D array ___")
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)
print(type(arr1))

___ 1D array ___
[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>


In [17]:
print("___ 2D array ___")
# 2D array
arr2= np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)


___ 2D array ___
[[1 2 3]
 [4 5 6]]
(2, 3)


In [18]:
print("___ zeros matrox ___")
# zeros 
arr3=np.zeros((3,4))
print(arr3)
print(arr3.shape)

___ zeros matrox ___
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)


In [19]:
print("___ ones matrix ___")
# ones array
arr4=np.ones((2,3))
print(arr4)
print(arr4.shape)


___ ones matrix ___
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [20]:
print("___ Identity matrix ___")
# identity  (show 1 diagnal)
arr5=np.identity(4)
print(arr5)
print(arr5.shape)

___ Identity matrix ___
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [21]:
print("___ Arange function ___")
# arrange 
arr7a=np.arange(10)
arr7b=np.arange(10,20)
arr7c=np.arange(1,10,2)
print(arr7a)
print(arr7b)
print(arr7c)
print(arr7c.shape)

___ Arange function ___
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[1 3 5 7 9]
(5,)


In [22]:
print("___ linespace function ___")
# linspace
arr8=np.linspace(10,20,10)
print(arr8)
print(arr8.shape)
print("Datatype  =>",arr8.dtype)  # float64
convert_to_other_datatype = arr8.astype('int')
print(convert_to_other_datatype)

___ linespace function ___
[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]
(10,)
Datatype  => float64
[10 11 12 13 14 15 16 17 18 20]


In [23]:
print("___ 2D array with functions(shape,ndim,Size,itemsize,dtype,astype) ___")
# 2D array
arr9=np.array([[[1,2],[3,4]]     ,     [[4,6],[7,8]]])
print(arr9)
print("shape     =>",arr9.shape)
print("Dimension =>",arr9.ndim)   # show matrix  1D 2D OR 3D
print("Size      =>",arr9.size)
print("Itemsize  =>",arr9.itemsize)
print("Datatype  =>",arr9.dtype)
#astype  (to convert to another datatype)
convert_to_other_datatype = arr9.astype('float')
print(convert_to_other_datatype)

___ 2D array with functions(shape,ndim,Size,itemsize,dtype,astype) ___
[[[1 2]
  [3 4]]

 [[4 6]
  [7 8]]]
shape     => (2, 2, 2)
Dimension => 3
Size      => 8
Itemsize  => 8
Datatype  => int64
[[[1. 2.]
  [3. 4.]]

 [[4. 6.]
  [7. 8.]]]


In [24]:
print("___ List and array  ___")
# List and array
lista= range(100)
arr10=np.arange(100)
print(lista)
print(arr10)
import sys
print(sys.getsizeof(7)*len(lista))
print(arr10.itemsize*arr10.size)

___ List and array  ___
range(0, 100)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
2800
800


In [25]:
print("___ Time count number in how many sec or milli sec ___")
# time
import time
x=range(100000)
y=range(100000,200000)
 
start_time = time.time()
c=[(x,y) for x,y in zip(x,y)]
print(time.time()-start_time)  # count  100000 in how many sec or milli sec

a=np.arange(100000)
b=np.arange(100000,200000)
c=a+b
print(time.time()-start_time)

___ Time count number in how many sec or milli sec ___
0.08747148513793945
0.08747148513793945
